### ISSUE TITLE
Error While uploading data 

### ISSUE THREAD

**Issue by jabbar86** [garbados/Cloudant-Uploader#3]
I am getting this error while uploading the data.

Uploading 91 docs...
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
  name: 'Error',
  scope: 'socket',
  errid: 'request',
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  description: 'read ECONNRESET',
  stacktrace:
   [ 'Error: read ECONNRESET',
     '    at _errnoException (util.js:1024:11)',
     '    at TCP.onread (net.js:615:25)' ] }
/Users/jabbar_memon/Documents/Jump360/Cal_Impact/csvtocloudant.js:66
        throw new Error(err);
        ^

Error: Error: error happened in your connection
    at /Users/jabbar_memon/Documents/Jump360/Cal_Impact/csvtocloudant.js:66:15
    at /Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/async/dist/async.js:3888:9
    at /Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/async/dist/async.js:988:17)
    at /Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/async/dist/async.js:969:16
    at /Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/async/dist/async.js:3885:13
    at Request._callback (/Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/nano/lib/nano.js:98:11)
    at self.callback (/Users/jabbar_memon/Documents/Jump360/Cal_Impact/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)

**Comment by garbados** [comment]
Sorry, this code is five years untouched and I don't really use Cloudant anymore. Feel free to fork the code, or use [couchimport](https://github.com/glynnbird/couchimport) which is still actively maintained.

To clarify the state of this project, I'm going to archive it.
